### ISSUE TITLE
opening project failed

### ISSUE THREAD

**Issue by mdsotoke** [PolygonHive/GASP-ALS#6]
I am unable to open this template in Unreal Engine because the file naming of the .uproject is not aligned with the naming conventions required by Unreal Editor. When I attempt to rename the file, it is no longer detected by the Unreal Editor. What is the solution to this issue?
![Screenshot 2024-07-12 110802](https://github.com/user-attachments/assets/4ff0471f-c8bc-43f9-a71c-adb56b73e7a7)

**Comment by TCMabe** [comment]
I’ll take a look at this later this morning and see what the solution is.Sent from my iPhoneOn Jul 12, 2024, at 12:09 AM, mdsotoke ***@***.***> wrote:﻿
I am unable to open this template in Unreal Engine because the file naming of the .uproject is not aligned with the naming conventions required by Unreal Editor. When I attempt to rename the file, it is no longer detected by the Unreal Editor. What is the solution to this issue?
Screenshot.2024-07-12.110802.png (view on web)

**Comment by vahid67** [comment]
I don't have this problem, but You can rename the `.uproject` file to test it out, renaming a blueprint project file name is allowed.

**Comment by IngCr3at1on** [comment]
Confirmed on Linux with 5.4.3.

**Comment by PolygonHive** [comment]
I removed the "-" from the name as it was also causing packaging issues
